language: d
sudo: false
dist: bionic

addons:
  apt:
    packages:
      - pkg-config
      - gcc-multilib
      - ninja-build
      - python3-pip
      - python3-setuptools

branches:
  only:
    - master

install:
  - pip3 install 'meson==0.53.1'

before_script:
  export PATH=$PATH:$PWD/.ntmp

script:
  - meson build && ninja -j8 -C build
  - ninja -j8 -C build test -v
  - git submodule update --init --recursive
  - make -B -C test/
  - dub test
