language: d
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - pkg-config
      - gcc-multilib

install:
  - pyenv global system 3.6
  - pip3 install 'meson>=0.45'
  - mkdir .ntmp
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip -o .ntmp/ninja-linux.zip
  - unzip .ntmp/ninja-linux.zip -d .ntmp

before_script:
  export PATH=$PATH:$PWD/.ntmp

script:
  - meson build && ninja -j8 -C build
  - ninja -j8 -C build test -v
  - git submodule update --init --recursive
  - make -B -C test/
